### ISSUE TITLE
Review README/Schedule and setup

### ISSUE THREAD

**Issue by sstevens2** [McMahonLab/git_wksp#1]
Hey @joshamilton,
I've been working on customizing this repo for the Git workshop.  If you get a chance, could you look over the main README/schedule and setup (see link in README) and let me know what you think?  
I mostly kept to the same amount of time the software carpentry workshop spends on these sections.  I'm hoping since our lab is mostly familiar with command line it will go a bit faster, if so I'll continue into the intro to github (Make changes from anywhere) section on the first day and the 2nd day will be just workflows.
I'm still working on customizing the other lessons.
Sarah

**Comment by sstevens2** [comment]
P.S. Please create pull requests with suggestions or fixes.  I'll be pushing directly to this repo and this will avoid conflicts.

**Comment by joshamilton** [comment]
Schedule and lessons look good to me so far. Probably should include some info about the McMahonLab org on Github. Do you think it would be worth discussing how to use Zissou for remotes or private repos?

**Comment by sstevens2** [comment]
I've never really looked at how to use zissou as a replacement for github.  With all the other changes I want to make (I want to take out the usage of the simplestats repo from software carpentry at the very least), I'm hesitant to learn this to add it.  But I'm kind of on the fence and could be persuaded otherwise.
Alternatively, I could easily add mention in the github section of bitbucket.  It has a different pricing structure than github.  You can have as many private repos as you want as long as you have less than 5 people using that repo.  So it isn't as good for organizations but better for individuals.  I use that for my private repos.
Using zissou would be useful if it were very very private, as in can't let any organization(even bitbucket or github) because it is sensitive data.  But I don't think we will really need to do that.  Given a bitbucket mention, do you think we should still go into how to use zissou in place of these web services?

**Comment by sstevens2** [comment]
P.S. Thanks for looking things over

**Comment by joshamilton** [comment]
I wasn't aware that Bitbucket had support for Git, thought it was just Mercurial. Mentioning Bitbucket should be fine instead of Zissou.

**Comment by sstevens2** [comment]
Yep.  You can use bitbucket with git.  I think they have a couple options, maybe svn too?  Ok if you think that it will be fine I'll not learn that usage for the workshop.
I'll leave the issue for you to close, if you think the schedule and setup look good now.

**Comment by sstevens2** [comment]
Thanks again for all your help with this!
