### ISSUE TITLE
Update Make incremental changes 2

### ISSUE THREAD

**Issue by sstevens2** [McMahonLab/git_wksp#5]

**Comment by sstevens2** [comment]
Fixed the breadcrumbs, still need to go through this one, at the very least take out the review of stuff they just learned 15 min before.

**Comment by sstevens2** [comment]
Decided not to take out the review because I think it will be good to have and the exercise at the beginning is good practice and setup.

**Comment by sstevens2** [comment]
@joshamilton If you have time, could you check over this lesson, particularly the branching and merging.  In the actual software carpentry material, they take the `stats.py` program they were working on in python section.  I didn't want to get too far into a language, so I just made it a fake python program, where they just add comments that are pretend functions.
If you don't have time, I can just go with it and the test will be if it makes sense to our students/labmates.

**Comment by joshamilton** [comment]
@sstevens2 I agree the new example is a bit artificial but it gets the point across. Folks should get the hang of it once they start branching and merging within their own projects, and they can always go back to the tutorial as a reference. I think what you have is fine and you can close the issue.
